### ISSUE TITLE
启动项目时（npm run dev）报错了，我是一个起步小白，正在学习中，还不太懂，还请多多

### ISSUE THREAD

**Issue by mzyailqq** [lijinke666/react-project-template#1]
![image](https://user-images.githubusercontent.com/1835371/28805413-6d7bc758-769c-11e7-9638-d0274f3c0f3b.png)
我的node版本是6.11.1，不知道又没关系, 8.2.1也试了下，报一样的错误

**Comment by lijinke666** [comment]
能看下你的 `config/index.js`  吗 ？ 有可能是当前你的设备端口666已经被占用了

**Comment by mzyailqq** [comment]
恩恩，可以啦，果然是端口号，谢谢大神啦，run起来啦
Duplicate of #

**Comment by lijinke666** [comment]
不是大神, 一起学习吧..
