### ISSUE TITLE
选用的react-router好像不是最新的

### ISSUE THREAD

**Issue by zhangwei900808** [lijinke666/react-project-template#2]
react-router4.0已经发布了，可以更新项目了

**Comment by lijinke666** [comment]
哈哈 是啊 , `react-router4` 出来很久了,一直没时间整, 惭愧啊, 
能提一个 `pr` 当然是极好的 :)

**Comment by lijinke666** [comment]
@zhangwei900808 
项目以升级到 `react-router4` + `webpack4` + `babel7`  
敬请试用
